DROP DATABASE IF EXISTS shopme;
CREATE DATABASE IF NOT EXISTS shopme ;
USE shopme;

CREATE TABLE IF NOT EXISTS users(
	id INT NOT NULL ,
	username VARCHAR(150) PRIMARY KEY NOT NULL,
    `password` VARCHAR(255) NOT NULl,
    `role` VARCHAR(50) NOT NULL
)